### PR TITLE
Increment the number of tiles automatically until it works

### PR DESCRIPTION
**Pull request by lguerard**

### CODE REVIEW

**Comment by tinevez** [comment]
Thanks! I see that you have an original approach.

But can we instead come up with an optimal tile size so that we do not have to repeat the process? I am afraid that if the process breaks for another reason than the tile size, we will make things worst.

Also (this is for my OCT) please use the imglib2 formatter for the code.

**Comment by lguerard** [comment]
> But can we instead come up with an optimal tile size so that we do not have to repeat the process? I am afraid that if the process breaks for another reason than the tile size, we will make things worst.

I tried to find a maximum number of pixels above which it failed, got to something around 16100000 but couldn't get the reasoning behind that limit so not sure how stable it would be for other users...

My approach was that it should either be a loop (as it is now) or implement a slider/text field for the number of tiles, but the 2nd option was way above my Java knowledge...

> Also (this is for my OCT) please use the imglib2 formatter for the code.

I would be happy to, but not sure what it would be... Is there any doc about it ?

**Comment by tinevez** [comment]
It looks like StarDist does not like tiles larger than 1000x1000. 

https://forum.image.sc/t/issue-with-trackmate-and-stardist-on-big-dataset/57976/2
https://forum.image.sc/t/issue-with-stardist-w-or-w-o-trackmate-with-large-images/60373/12

Maybe this is it?

**Comment by lguerard** [comment]
Hmmm, on my image it was working until 16 000 000 pixels somehow, which would be 16 tiles if we use the 1000x1000 limit.

I had implemented a hard limit before switching to the loop approach, do you want me to switch back to it ?

**Comment by lguerard** [comment]
Ok reverted back to the normal call and used 1M pixels as the max size.

The tile calculation is not taking into consideration other dimension than X and Y but that shouldn't be a problem since StarDist only runs on 2D images, right ?

**Comment by tinevez** [comment]
Excellent. 
Do we have large images to test the new PR? Something that fails with the current version and works with the PR?

**Comment by lguerard** [comment]
I did try it with a user's image and it worked with the new PR while it wasn't before. 

Another way to test is to create empty images with a big size and check if 1) it worked, if so 2) how many tiles it used from the console.

**Comment by tinevez** [comment]
Thanks! I will take it from there.

**Comment by tinevez** [comment]
Don't worry about the build process failing for now.

**Comment by lguerard** [comment]
Awesome, thanks a lot ! :)

**Pull request merged**
